---
title: "Day of the Race"
output: html_notebook
---

It’s the day of a citywide track race and you’re helping out your friends! You’ll be adding their jersey and color information to a list, helping display their information, and building a useful function to figure out what place your friends came in the race.

```{r}
# create friends vector here:
friends <- c('Megan', 'Janet', 'Tina')
```

```{r}
# add on to the list here:
info_list <- list(
  Esther = list(
    jersey = 3432,
    color = "purple"
  ),
  Feng = list(
    jersey = 4221,
    color = "blue"
  ),
  Megan = list(
    jersey = 1363,
    color = "green"
  ),
  Janet = list(
    jersey = 6729,
    color = "green"
  ),
  Tina = list(
    jersey = 7501,
    color = "orange"
  )
)
```

```{r}
print_information <- function(name) {
  print(paste(name, "is #", info_list[[name]]$jersey, "wearing the color", info_list[[name]]$color))
}
# call the print_information function on the friends vector:
lapply(friends, print_information)
```

```{r}
race_results <- c("Gi", "Francesca", "Lea", "Vivian", "Jessica", "Esther", "Mary", "Yasmina", "Megan", "Janet", "Tiffany", "Kishan", "Feng", "Z", "Tina")
```

```{r}
# write find_place() here:
find_place <- function(runner){
  for (place in 1:length(race_results)){
    if (race_results[place] == runner){
      return(place)
    }
  }
  return(length(race_results) + 1)
}

```


```{r}
# call and apply find_place() here:
lapply(friends, find_place)

```