---
title: "Page Visits Funnel"
output: html_notebook
---

```{r message = FALSE, error=TRUE}
# load packages
library(readr)
library(dplyr)
```

```{r message = FALSE, error=TRUE}
# load data
visits <- read_csv("visits.csv")
cart <- read_csv("cart.csv")
checkout <- read_csv("checkout.csv")
purchase <- read_csv("purchase.csv")
```

```{r error=TRUE}
# inspect data frames
head(visits)
head(cart)
head(checkout)
head(purchase)
```

```{r error=TRUE}
# define visits_cart here:

visits_cart <- visits %>%
  left_join(cart)
visits_cart


```

```{r error=TRUE}
# define total_visits here:
total_visits <- nrow(visits)
print(paste('The length of the total visits is', total_visits))
```

```{r error=TRUE}
# define visit_no_cart here:
visit_no_cart <- visits_cart %>%
  filter(is.na(cart_time))
visit_no_cart


```

```{r error=TRUE}
# calculate visit_no_cart_percent here:
visit_no_cart_percent = nrow(visit_no_cart) / nrow(visits_cart) * 100
print(paste(visit_no_cart_percent, '%'))

```

```{r error=TRUE}
# define cart_checkout here:
cart_checkout <- cart %>%
  left_join(checkout)




```

```{r error=TRUE}
# define total_carts here:
total_carts <- nrow(carts)
print(paste('The length of the total carts is', total_carts))

```

```{r error=TRUE}
# define cart_no_checkout here:
cart_no_checkout <- cart %>%
  left_join(checkout) %>%
  filter(is.na(checkout_time)) %>%
  nrow()



```

```{r error=TRUE}
# calculate cart_no_checkout_percent here:
cart_no_checkout_percent = cart_no_checkout / nrow(cart_checkout) * 100
print(paste(cart_no_checkout_percent, '%'))

```

```{r error=TRUE}
# define all_data here:
all_data <- visits %>%
  left_join(cart) %>%
  left_join(checkout) %>%
  left_join(purchase)
all_data




```

```{r error=TRUE}
# define total_checkout here:
total_checkout <- nrow(checkout)
print(paste('The length of the total carts is', total_checkout))

```

```{r error=TRUE}
# define checkout_no_purchase here:
checkout_purchase <- checkout %>%
  left_join(purchase)
checkout_purchase

checkout_no_purchase <- checkout_purchase %>%
  filter(is.na(purchase_time)) %>%
  nrow()
checkout_no_purchase



```

```{r error=TRUE}
# calculate checkout_no_purchase_percent here:
checkout_no_purchase_percent <- checkout_no_purchase / nrow(checkout_purchase) * 100
print(paste(checkout_no_purchase_percent, '%'))

```

```{r error=TRUE}
# update all_data with time_to_purchase column here:
all_data <- all_data %>%
  mutate(time_to_purchase = purchase_time - visit_time)

```

```{r error=TRUE}
# inspect the updated all_data data frame here:
head(all_data)
```

```{r error=TRUE}
# define time_to_purchase here:
time_to_purchase <- all_data %>%
  summarize(mean_time = mean(time_to_purchase, na.rm = TRUE))
time_to_purchase


```